# template-meta:
#   id: google-groups
#   parameters:
#     required: [slug, image, port]
#     optional: []
#   secrets:
#     per_instance: []
#     per_host_referenced: []
#   volumes: []
---
apiVersion: v1
kind: Pod
metadata:
  name: google-groups-{{.slug}}
  labels:
    podman-api/template: google-groups
    podman-api/slug: {{.slug}}
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: {{.image}}
      ports:
        - containerPort: 8080
          hostPort: {{.port}}
          hostIP: 127.0.0.1
